Minalanguage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from jet.dashboard.dashboard_modules import google_analytics_views

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mina.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
]

mina/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.user_login, name='user_login'),
    url(r'^logout$', views.user_logout, name='user_logout'),
    url(r'^send_message/', views.send_message, name='send_message'),
    url(r'^home/', views.user_home, name='user_home'),
    url(r'^privacy_notice/', views.privacy_notice, name='privacy_notice'),
    url(r'^contact_us/', views.contact_us, name='contact_us'),
    url(r'^consultation/', views.free_consultation, name='free_consultation'),
    url(r'^calendar/$', views.show_calendar, name='show_calendar'),
    url(r'^book/$', views.book_meeting, name='book_meeting'),
    url(r'^subscribe/$', views.subscribe, name='subscribe'),
    url(r'^subs/unsub/(?P<trans_id>[\w-]+)$', views.unsubscribe, name='unsubscribe'),
    url(r'^outline/overview/$', views.outline_overview, name='outline_overview'),
    url(r'^outline/add_root/$', views.add_root_outline, name='add_root_outline'),
    url(r'^outline/view/(?P<program_type>[\w-]+)$', views.show_outline, name='show_outline'),
    url(r'^outline/edit/$', views.edit_outline, name='edit_outline'),
    url(r'^outline/list/(?P<program_type>[\w-]+)$', views.show_outline, name='list_outline'),
    url(r'^outline/remove/$', views.remove_outline, name='remove_outline'),
    url(r'^outline/remove_related/$', views.remove_related_item, name='remove_related_item'),
    url(r'^outline/add_related/$', views.add_related_item, name='add_related_item'),
    url(r'^outline/get_related_items$', views.get_related_items, name='get_related_items'),
    url(r'^progress/edit/$', views.edit_progress, name='edit_progress'),
    url(r'^file/list/$', views.file_list, name='file_list'),
    url(r'^file/manage/$', views.manage_files, name='manage_files'),
    url(r'^file/manage/(?P<user_id>[\w-]+)$', views.manage_user_files, name='manage_user_files'),
    url(r'^file/upload/(?P<user_id>[\w-]+)$', views.upload_files, name='upload_files'),
    url(r'^file/delete/(?P<file_id>[\w-]+)/$', views.delete_file, name='delete_file'),
    url(r'^meetings/list/$', views.list_meetings, name='list_meetings'),
    url(r'^meetings/superbook/$', views.super_book_meeting, name='super_book_meeting'),
    url(r'^meetings/edit$', views.change_meeting, name='change_meeting'),
    url(r'^meetings/remove/(?P<booking_id>[\w-]+)', views.remove_meeting, name='remove_meeting'),
    url(r'^meetings/get_meetings', views.get_all_meetings, name='get_all_meetings'),
]

mina/models.py
import os
from datetime import datetime
from uuid import uuid4

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_delete
from django.db.models.signals import post_save
from django.dispatch import receiver
from mptt.models import MPTTModel, TreeForeignKey


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    new_student = models.BooleanField(default=True)
    locale = models.CharField(max_length=10, blank=True, null=True)
    social_id = models.CharField(max_length=255, blank=True)
    login_type = models.CharField(max_length=10, null=True, blank=True)
    profile_photo = models.FileField(upload_to='./media/profile_pics')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class Booking(models.Model):
    TYPE = (
        ('online', 'Online'),
        ('in-person', 'In Person')
    )
    CLASS_TYPE = (
        ('chinese', 'Chinese'),
        ('korean', 'Korean')
    )
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='booked_user')
    book_type = models.CharField(max_length=10, choices=TYPE, null=True, blank=True)
    start = models.DateTimeField()
    end = models.DateTimeField()
    repeat = models.BooleanField(default=False)
    class_type = models.CharField(max_length=10, null=True, blank=True, choices=CLASS_TYPE)
    class_location = models.CharField(max_length=255, null=True, blank=True, default="Walnut Creek, CA")
    transaction_id = models.CharField(max_length=50, null=True, blank=True)
    transaction_amount = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s - %s to %s" % (self.user.get_full_name(),
                                  datetime.strftime(self.start, '%m/%d/%y %H:%M'),
                                  datetime.strftime(self.end, '%m/%d/%y %H:%M'))

    class Meta:
        ordering = ['start']

    @property
    def is_in_past(self):
        return datetime.now() > self.end


def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid4(), ext)
    return os.path.join('./files/', filename)


class Files(models.Model):
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='file_to_user')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    file = models.FileField(upload_to=user_directory_path)
    name = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return "%s - %s" % (self.to_user.get_full_name(), self.name)


@receiver(post_delete, sender=Files)
def file_delete(sender, instance, **kwargs):
    if instance.file:
        instance.file.delete(False)


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="customer")
    customer_id = models.CharField(max_length=50, blank=True, null=True)
    customer_email = models.CharField(max_length=50, blank=True, null=True)
    total_paid = models.IntegerField(null=True, blank=True)


class Outline(MPTTModel):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    program = models.CharField(max_length=50, null=True, blank=True)
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True,
                            on_delete=models.CASCADE)

    def __str__(self):
        return "%s" % self.name

    class MPTTMeta:
        order_insertion_by = ['name']


class Progress(models.Model):
    outline = models.ForeignKey(Outline, on_delete=models.CASCADE, related_name='outline_progress')
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='student_progress')
    passed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class RelatedFiles(models.Model):
    outline = models.ForeignKey(Outline, on_delete=models.CASCADE, related_name='related_files')
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='related_to')
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE, null=True, blank=True, related_name='outline_booking')
    file = models.ForeignKey(Files, on_delete=models.CASCADE, null=True, blank=True, related_name='outline_file')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

mina/views.py
import json
import os
import random
from datetime import datetime, timedelta

import requests
import stripe
from decouple import config
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.utils.text import slugify

from .forms import BookingForm, FileForm, OutlineForm
from .models import Booking, Files, Customer, Outline, Progress, RelatedFiles

NAVER_CLIENT_ID = config('NAVER_CLIENT_ID')
NAVER_CLIENT_SECRET = config('NAVER_CLIENT_SECRET')


# Create your views here.

def user_login(request):
    if request.user.is_authenticated and not request.user.is_anonymous:
        return redirect('user_home')
    else:
        return render(request, 'index.html', {
        })


def user_logout(request):
    auth_logout(request)
    return redirect('user_login')


def privacy_notice(request):
    return render(request, 'main_parts/privacy_notice.html', {})


def send_message(request):
    recaptcha = request.POST.get('g-recaptcha-response')
    r = requests.post('https://www.google.com/recaptcha/api/siteverify', {
        "response": recaptcha,
        "secret": "6Ld55iAUAAAAALrIF3nwtqeMUruRckJvQ6F3-VeI"
    })
    if request.method == "POST" and request.POST.get('email') and r.json()['success'] is True:
        person = request.POST.get('person')
        email = request.POST.get('email')
        subject = "Message received on MinaJeong.com"
        message = "(%s:%s) sent you the following message: \n Subject: \"%s\" \n Message: \"%s\"" % (
            person, email, request.POST.get('subject'), request.POST.get('message'))
        send_mail(
            subject,
            message,
            'admin@minajeong.com',
            ['zxoct11@gmail.com', 'onhout@gmail.com'],
            fail_silently=False, )
    return redirect('/')


@login_required
def book_meeting(request):
    if 'STRIPE_SECRET_KEY' in os.environ:
        stripe.api_key = os.environ['STRIPE_SECRET_KEY']
    else:
        stripe.api_key = config('STRIPE_SECRET_KEY')
    if request.method == "POST" and request.user.is_authenticated:
        json_loads = json.loads(request.POST.get('booking'))
        charge = stripe.Charge.create(
            source=json_loads["stripeToken"]['id'],
            currency="usd",
            description="Mina's Language Class",
            amount=json_loads["cost"],
            metadata={"order_from": request.user.get_full_name()}
        )
        obj, customer = Customer.objects.get_or_create(user=request.user)
        if charge["status"] == "succeeded":
            if obj.customer_id is None:
                obj.customer_email = charge["source"]["name"]
                obj.save()
            for booking in json_loads["bookings"]:
                book_form = BookingForm(booking)
                if book_form.is_valid():
                    msg_html = render_to_string('email_templates/new_meeting.html', {
                        "name": request.user.get_full_name(),
                        "start": datetime.strptime(booking["start"], '%Y-%m-%d %H:%M:%S'),
                        "end": datetime.strptime(booking["end"], '%Y-%m-%d %H:%M:%S'),
                        "class_type": booking["class_type"],
                        "book_type": booking["book_type"]
                    })
                    message = strip_tags(msg_html)
                    email_list = ['zxoct11@gmail.com', request.user.email]
                    for email in email_list:
                        send_mail(
                            'Thank you for booking a meeting',
                            message,
                            'noreply@minajeong.com',
                            [email],
                            html_message=msg_html,
                            fail_silently=False, )
                    form = book_form.save(commit=False)
                    form.client_ip = json_loads["stripeToken"]["client_ip"]
                    form.transaction_id = charge["id"]
                    form.transaction_amount = booking["transaction_amount"]
                    form.user = request.user
                    form.save()

        return redirect('show_calendar')


@login_required
def subscribe(request):
    if 'STRIPE_SECRET_KEY' in os.environ:
        stripe.api_key = os.environ['STRIPE_SECRET_KEY']
    else:
        stripe.api_key = config('STRIPE_SECRET_KEY')
    if request.method == "POST" and request.user.is_authenticated:
        json_loads = json.loads(request.POST.get('booking'))
        obj, customer = Customer.objects.get_or_create(user=request.user)
        if obj.customer_id is None:
            stripe_customer = stripe.Customer.create(
                description="minajeong.com student: %s" % request.user.get_full_name(),
                email=request.user.email or None,
                source=json_loads["stripeToken"]["id"]
            )
            obj.customer_id = stripe_customer.stripe_id
            obj.save()
        else:
            stripe_customer = stripe.Customer.retrieve(obj.customer_id)

        sub = stripe.Subscription.create(
            customer=stripe_customer.id,
            plan="month_plan"
        )
        if sub.status == "active":
            for booking in json_loads["bookings"]:
                msg_html = render_to_string('email_templates/new_sub.html', {
                    "name": request.user.get_full_name(),
                    "start": datetime.strptime(booking["start"], '%Y-%m-%d %H:%M:%S'),
                    "end": datetime.strptime(booking["end"], '%Y-%m-%d %H:%M:%S'),
                    "class_type": booking["class_type"],
                    "book_type": booking["book_type"]
                })
                message = strip_tags(msg_html)
                email_list = ['zxoct11@gmail.com', request.user.email]
                for email in email_list:
                    send_mail(
                        'Thank you for subscribing!',
                        message,
                        'noreply@minajeong.com',
                        [email],
                        html_message=msg_html,
                        fail_silently=False, )
                for i in range(52):
                    start_time = datetime.strptime(booking["start"], '%Y-%m-%d %H:%M:%S') + timedelta(days=(i * 7))
                    end_time = datetime.strptime(booking["end"], '%Y-%m-%d %H:%M:%S') + timedelta(days=(i * 7))
                    book_form = BookingForm(booking)
                    if book_form.is_valid():
                        form = book_form.save(commit=False)
                        form.start = start_time
                        form.end = end_time
                        form.repeat = True
                        form.transaction_id = sub["id"]
                        form.transaction_amount = 100
                        form.user = request.user
                        form.save()
        return redirect('show_calendar')


@login_required
def unsubscribe(request, trans_id):
    if 'STRIPE_SECRET_KEY' in os.environ:
        stripe.api_key = os.environ['STRIPE_SECRET_KEY']
    else:
        stripe.api_key = config('STRIPE_SECRET_KEY')
    sub = Booking.objects.filter(transaction_id=trans_id)[0]
    if sub.user == request.user or request.user.is_staff:
        stripe_sub = stripe.Subscription.retrieve(trans_id)
        Booking.objects.filter(transaction_id=trans_id).delete()
        stripe_sub.delete()
        msg_html = render_to_string('email_templates/lost_sub.html', {
            "name": request.user.get_full_name()
        })
        message = strip_tags(msg_html)
        email_list = ['zxoct11@gmail.com', request.user.email]
        for email in email_list:
            send_mail(
                'Sorry to see you go.',
                message,
                'noreply@minajeong.com',
                [email],
                html_message=msg_html,
                fail_silently=False, )
        return redirect('list_meetings')
    return redirect('/')


@login_required
def show_calendar(request):
    try:
        next_meeting = Booking.objects.filter(user=request.user, start__gt=datetime.today())[0]
    except:
        next_meeting = 'none'
    return render(request, 'meeting/book.html', {
        'next_meeting': next_meeting
    })


@login_required
def remove_meeting(request, booking_id):
    if request.user.is_staff:
        Booking.objects.get(id=booking_id).delete()
        return redirect('list_meetings')
    return redirect('/')


@login_required
def super_book_meeting(request):
    if request.method == 'POST' and request.user.is_staff:
        book_form = BookingForm(request.POST)
        if book_form.is_valid():
            form = book_form.save(commit=False)
            form.user = request.user
            form.save()
            return JsonResponse({"status": "success"})
        return JsonResponse({"status": "failed"})


@login_required
def list_meetings(request):
    before = datetime.now() - timedelta(days=30)
    after = datetime.now() + timedelta(days=30)
    sub_list = []
    subscription_list = Booking.objects.values_list('transaction_id').order_by('-repeat').distinct()
    if request.user.is_staff:
        meeting_list = Booking.objects.filter(start__gte=before, end__lte=after)
        for sub in subscription_list:
            try:
                sub_list.append(Booking.objects.filter(transaction_id=sub[0], repeat=True)[0])
            except:
                pass
    else:
        meeting_list = Booking.objects.filter(user=request.user, start__gte=before, end__lte=after)
        for sub in subscription_list:
            try:

mina/templates/files/list_files.html
{% extends 'home.html' %}
{% load render_bundle from webpack_loader %}
{% block title %}File List{% endblock %}
{% block user_home %}
    <h2 class="text-center">File List</h2>
    {% if file_list %}
        <div class="table-responsive">
            <table class="table table-hover table-striped table-bordered">
                <thead>
                <tr>
                    <th>File</th>
                    <th>Date Uploaded</th>
                </tr>
                </thead>
                <tbody>
                {% for file in file_list %}
                    <tr>
                        <td><a href="http://minalanguage.s3.amazonaws.com/{{ file.file }}">{{ file.name }}</a></td>
                        <td>{{ file.updated_at }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <h4 class="text-center">Nothing yet!</h4>
        <div class="text-center">
            <p>Mina will post files here for you and relate them to each lectures</p>
            <p>You can download the files under each lectures and under this table</p>
        </div>
    {% endif %}
{% endblock %}

mina/templates/files/manage_files.html
{% extends 'Global.html' %}
{% load render_bundle from webpack_loader %}
{% block title %}User List{% endblock %}
{% block content %}
    <h1 class="text-center">Manage User Files</h1>
    {% if user_list %}
        <h4>Students</h4>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-sm">
                <thead>
                <tr>
                    <th>First name</th>
                    <th class="hidden-xs">Last name</th>
                    <th class="hidden-xs">Username/Email</th>
                    <th class="hidden-xs">Last login</th>
                    <th class="hidden-xs">Total Files</th>
                    <th class="hidden-xs">Total Paid</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for user in user_list %}
                    {% if user.totalPaid.totalPaid %}
                        <tr>
                            <td>{{ user.first_name }}</td>
                            <td class="hidden-xs">{{ user.last_name }}</td>
                            <td class="hidden-xs">{{ user.username }}</td>
                            <td class="hidden-xs">{{ user.last_login }}</td>
                            <td class="hidden-xs">{{ user.totalFiles }}</td>
                            <td class="hidden-xs">
                                ${% if user.totalPaid.totalPaid %}{{ user.totalPaid.totalPaid }}{% else %}0{% endif %}
                            </td>
                            <td>
                                <a href="{% url 'manage_user_files' user.id %}" class="btn btn-primary">Upload Files</a>
                                <div class="dropdown" style="display:inline">
                                    <button class="btn btn-info dropdown-toggle" type="button"
                                            id="studentDropDownButton"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Progress
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="studentDropDownButton">
                                        {% for program in program_list %}
                                            <a class="dropdown-item"
                                               href="{% url 'show_outline' program.program %}?student_id={{ user.id }}">
                                                {{ program.name }}
                                            </a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>

        <h4>Whatever people</h4>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-sm table-responsive">
                <thead>
                <tr>
                    <th>First name</th>
                    <th class="hidden-xs">Last name</th>
                    <th class="hidden-xs">Username/Email</th>
                    <th class="hidden-xs">Last login</th>
                    <th class="hidden-xs">Total Files</th>
                    <th class="hidden-xs">Total Paid</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for user in user_list %}
                    {% if not user.is_staff and not user.totalPaid.totalPaid %}
                        <tr class="text-muted" style="font-style: italic">
                            <td>{{ user.first_name }}</td>
                            <td class="hidden-xs">{{ user.last_name }}</td>
                            <td class="hidden-xs">{{ user.username }}</td>
                            <td class="hidden-xs">{{ user.last_login }}</td>
                            <td class="hidden-xs">{{ user.totalFiles }}</td>
                            <td class="hidden-xs">
                                ${% if user.totalPaid.totalPaid %}{{ user.totalPaid.totalPaid }}{% else %}0{% endif %}
                            </td>
                            <td>
                                <a href="{% url 'manage_user_files' user.id %}" class="btn btn-primary">Upload Files</a>
                                <div class="dropdown" style="display:inline">
                                    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown"
                                            aria-haspopup="true" aria-expanded="false" id="whateverDropDown">
                                        Classes
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="whateverDropDown">
                                        {% for program in program_list %}
                                            <a class="dropdown-item"
                                               href="{% url 'show_outline' program.program %}?student_id={{ user.id }}">
                                                {{ program.name }}
                                            </a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}

mina/templates/files/manage_user_files.html
{% extends 'Global.html' %}
{% load render_bundle from webpack_loader %}
{% block title %}Files{% endblock %}
{% block content %}
    <h1 class="text-center">Manage {{ this_user.get_full_name }}'s files</h1>
    <div class="panel panel-default">
        <div class="panel-heading">File List</div>
        <div class="panel-body">
            <button type="button"
                    class="btn btn-primary js-upload-files">
                <span class="glyphicon glyphicon-cloud-upload"></span> Upload Files
            </button>

            <div class="progress-container progress-primary" style="display:none">
                <div class="progress" style="margin: 5px 0">
                    <div class="progress-bar" role="progressbar" style="width: 0;"></div>
                    <p class="text-center progress-text"></p>
                </div>
            </div>


            <input id="id_file" type="file" name="file" multiple
                   style="display: none;"
                   data-url="{% url 'upload_files' this_user.id %}"
                   data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover" id="file_table">
                <thead>
                <tr>
                    <th>File</th>
                    <th>Date Uploaded</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for file in file_list %}
                    <tr>
                        <td><a href="http://minalanguage.s3.amazonaws.com/{{ file.file }}">{{ file.name }}</a></td>
                        <td>{{ file.created_at }}</td>
                        <td><a href="{% url 'delete_file' file.id %}"
                               data-csrftoken='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'
                               data-file_id="{{ file.id }}"
                               class="btn btn-danger delete_file">Delete</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}